const API_URL = "http://127.0.0.1:8000";

// DOM Elements
const statusIndicator = document.getElementById("api-status");
const pulseDot = document.querySelector(".pulse-dot");
const regimeCircle = document.getElementById("regime-circle");
const regimeId = document.getElementById("regime-id");
const predValue = document.getElementById("prediction-value");
const predDirection = document.getElementById("prediction-direction");
const simulateBtn = document.getElementById("simulate-btn");

let isLiveMode = false;
let pollingInterval = null;

// Check API Health
async function checkHealth() {
    try {
        const res = await fetch(`${API_URL}/health`);
        if (res.ok) {
            statusIndicator.textContent = "Backend Connected";
            pulseDot.classList.add("online");
        }
    } catch (error) {
        statusIndicator.textContent = "Backend Offline - Run 'uvicorn src.api.main:app'";
        pulseDot.classList.remove("online");
    }
}

// Poll the latest state generated by the Websocket client
async function pollLatestState() {
    try {
        const res = await fetch(`${API_URL}/predict/latest`);
        if (res.ok) {
            const data = await res.json();
            
            // Only update if the websocket has actually sent data
            if (data.timestamp > 0) {
                updateDashboard(data.prediction, data.regime);
            } else {
                predDirection.textContent = "Waiting for Binance Live Stream (needs 60m buffer)...";
            }
        }
    } catch (err) {
        console.error("Polling Error", err);
    }
}

// Toggle Live Stream Mode
function toggleLiveMode() {
    isLiveMode = !isLiveMode;
    
    if (isLiveMode) {
        simulateBtn.textContent = "Stop Live Feed";
        simulateBtn.style.background = "linear-gradient(135deg, #ef4444, #b91c1c)";
        predDirection.textContent = "Connecting to Binance stream...";
        
        // Start polling every 2 seconds
        pollingInterval = setInterval(pollLatestState, 2000);
    } else {
        simulateBtn.textContent = "Connect to Live Data Feed";
        simulateBtn.style.background = "linear-gradient(135deg, var(--primary), var(--accent))";
        predDirection.textContent = "Stream disconnected.";
        
        clearInterval(pollingInterval);
    }
}

function updateDashboard(prediction, regime) {
    // Update Regime UI
    regimeId.textContent = regime;
    regimeCircle.className = `regime-circle r${regime}`;

    // Update Prediction UI
    const percent = (prediction * 100).toFixed(4);
    predValue.textContent = `${percent > 0 ? '+' : ''}${percent}%`;
    
    if (prediction > 0) {
        predValue.className = "positive";
        predDirection.textContent = "Bullish Outlook (Live)";
    } else {
        predValue.className = "negative";
        predDirection.textContent = "Bearish Outlook (Live)";
    }
}

// Event Listeners
simulateBtn.addEventListener("click", toggleLiveMode);

// Init
checkHealth();
setInterval(checkHealth, 5000);
